apiVersion: v1
kind: ConfigMap
metadata:
  name: anythingllm-config
  namespace: anythingllm
  labels:
    app: anythingllm
data:
  STORAGE_DIR: "/app/server/storage"
  LLM_PROVIDER: "ollama"
  OLLAMA_BASE_PATH: "http://ollama.ollama.svc.cluster.local:11434"
