apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-data
  namespace: anythingllm
  labels:
    app: anythingllm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
